### ISSUE TITLE
Suggestion: Change the placeholder firing sound to the unused Bandit rifle sound.

### ISSUE THREAD

**Issue by Moffein** [BogRtM/Deputy#1]
Played a bit of Deputy and loved her playstyle! Noticed she's currently using Commando's Suppressive Fire sound for her attacks, which is kind of quiet. I think the unused Alpha Bandit fire sound (Play_bandit_M1_shot) would feel a lot punchier!

**Comment by BogRtM** [comment]
I'm happy to hear you like her! I tried out the SFX and it does sound a lot better! I'll change it in a coming patch.
