### ISSUE TITLE
Nullref spam when used with Regigigas

### ISSUE THREAD

**Issue by Moffein** [BogRtM/Deputy#8]
When Regigigas (survivor version, but probably applies to boss version too) gets hit by elite enemies, the console gets spammed with errors related to the AddTimedBuff hook. Happens when only Regigigas + Deputy are installed.
[LogOutput.log](https://github.com/BogRtM/Deputy/files/11610075/LogOutput.log)

**Comment by TheTimeSweeper** [comment]
fixed on regigigas's end
